[versions]
agp = "8.13.0"
gson = "2.13.2"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
constraintlayout = "2.2.1"
navigationFragmentKtx = "2.9.5"
navigationUiKtxVersion = "2.9.5"
legacySupportV4 = "1.0.0"
openaiJava = "4.6.1"
preference = "1.2.1"
recyclerview = "1.4.0"
junitJupiter = "6.0.0"
espressoContrib = "3.7.0"
testRules = "1.7.0"
media3Common = "1.8.0"
securityCrypto = "1.1.0"
uiautomator = "2.3.0"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "preference" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
openai-java = { module = "com.openai:openai-java", version.ref = "openaiJava" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtxVersion" }
androidx-legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junitJupiter" }
androidx-espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espressoContrib" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "testRules" }
androidx-media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "media3Common" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junitJupiter" }
androidx-security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "securityCrypto" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

